hanes/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    path('zavody/',
        include('zavody.urls', namespace='zavody')),
    path('lide/',
        include('lide.urls', namespace='lide')),
    path('kluby/',
        include('kluby.urls', namespace='kluby')),
    path('zavodnici/',
        include('zavodnici.urls', namespace='zavodnici')),
    path('pohary/',
        include('pohary.urls', namespace='pohary')),

    path('zalohovat_databazi/',
        login_required(views.backup_database), name='backup_database'),
    path('flatpages/editace/<int:pk>/',
        login_required(views.FlatPageUpdate.as_view()), name='flatpage_editace'),
    path('',
        views.uvod, {'url': '/uvod/'}, name='uvod'),

    # django
    path('admin/', admin.site.urls),
    path('accounts/',
        include('django.contrib.auth.urls')),
]

if settings.TEMPLATE_DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

kluby/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import *

app_name = 'kluby'
urlpatterns = [
    # LISTs
    path('',
        KlubyListView.as_view(), name='kluby_list'),

    # DETAILs
    path('detail/<str:slug>/',
        KlubDetailView.as_view(), name='klub_detail'),
    path('editace/<str:slug>/',
        login_required(KlubUpdateView.as_view()), name='klub_update'),

    # AUTOCOMPLETEs
    path('klub_autocomplete/',
        klub_autocomplete, name='klub_autocomplete'),
]

lide/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import *

app_name='lide'
urlpatterns = [
    # LISTs
    path('',
        clovek_list, name='lide_list'),

    # DETAILs
    path('detail/<str:slug>/',
        ClovekDetailView.as_view(), name='clovek_detail'),
    path('editace/<str:slug>/',
        login_required(clovek_update), name='clovek_update'),

    # IMPORTs
    path('import_csv/',
        LideImportCSV.as_view(), name='import_csv'),

    # AUTOCOMPLETEs
    path('clovek_autocomplete/',
        clovek_autocomplete, name='clovek_autocomplete'),
    path('rocnik/<int:rocnik_pk>/clovek_autocomplete/',
        clovek_autocomplete, name='clovek_autocomplete'),

    # UTILITY
    path('duplicity/',
        duplicity, name='duplicity'),
]

zavody/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required

from .views import *

app_name='zavody'
urlpatterns = [
    # LISTs
    path('',
        ZavodyListView.as_view(),
        name='zavody_list'),

    # DETAILs
    path('detail/<int:pk>/',
        ZavodDetailView.as_view(),
        name='zavod_detail'),
    path('rocnik/<int:pk>/detail/',
        RocnikDetailView.as_view(),
        name='rocnik_detail'),
    path('rocnik/<int:pk>/startovne/',
        StartovneRocnikuDetailView.as_view(),
        name='startovne_rocniku_detail'),
    path('kategorie/<int:pk>/',
        KategorieDetailView.as_view(),
        name='kategorie_detail'),
    path('rocnik/<int:rocnik_pk>/vysledkova_listina/',
        vysledkova_listina,
        name='vysledkova_listina'),
    path('rocnik/<int:pk>/startovni_casy/',
        login_required(StartovniCasyView.as_view()),
        name='startovni_casy'),

    # CREATEs
    path('zavod/novy/',
        ZavodPridejView.as_view(),
        name='zavod_pridani'),
    path('<str:slug>/rocnik/novy/',
        RocnikPridejView.as_view(),
        name='rocnik_pridani'),

    # UPDATEs
    path('rozkategorizovat_zavodniky/<int:rocnik_pk>/',
        login_required(rozkategorizovat_zavodniky),
        name='rozkategorizovat_zavodniky'),
    path('formular_startera/<int:rocnik_pk>/',
        login_required(formular_startera),
        name='formular_startera'),
    path('zavod/<int:pk>/editace/',
        ZavodUpdateView.as_view(),
        name='zavod_editace'),
    path('rocnik/<int:pk>/editace/',
        RocnikUpdateView.as_view(),
        name='rocnik_editace'),
    path('kategorie/<int:pk>/editace/',
        KategorieUpdateView.as_view(),
        name='kategorie_editace'),

    # DELETE
    path('rocnik/<int:pk>/smazat/',
        RocnikDeleteView.as_view(),
        name='rocnik_smazani'),
    path('zavod/<int:pk>/smazat/',
        ZavodDeleteView.as_view(),
        name='zavod_smazani'),
    # path('kategorie/<int:pk>/smazat/',
    #     KategorieDeleteView.as_view(),
    #     name='kategorie_smazani'),

    # FORMs
    path('pridani_zavodniku/rocnik/<int:pk>/',
        login_required(pridani_zavodniku),
        name='pridani_zavodniku'),
    path('import_zavodniku/rocnik/<int:pk>/',
        login_required(ImportZavodnikuView.as_view()),
        name='import_zavodniku'),
    path('rocnik/<int:rocnik_pk>/startovni_listina/',
        startovni_listina,
        name='startovni_listina'),
    path('rocnik/<int:rocnik_pk>/startovni_listina/<str:ordering_str>/',
        startovni_listina,
        name='startovni_listina'),
    path('rocnik/<int:rocnik_pk>/cilovy_formular/',
        login_required(cilovy_formular),
        name='cilovy_formular'),
    path('rocnik/<int:rocnik_pk>/import_souboru_casu/txt/',
        login_required(ImportCasuSouborView.as_view()),
        name='import_souboru_casu_txt'),
    path('rocnik/<int:rocnik_pk>/import_textu_casu/',
        login_required(ImportCasuTextView.as_view()),
        name='import_textu_casu'),
    path('rocnik/<int:rocnik_pk>/zpracovani_importovanych_casu/txt/',
        login_required(ZpracovaniImportovanychCasuTxtView.as_view()),
        name='zpracovani_importovanych_casu_txt'),

    # AJAX
    path('kategorie/<int:pk>/startovni_casy/upravit/',
        login_required(AjaxKategorieStartovniCasyUpdateView.as_view()),
        name='ajax_kategorie_startovni_casy_update'),

    # EXPORT
    path('rocnik/<int:rocnik_pk>/startovka_export/',
        startovka_export,
        name='startovka_export'),
    path('rocnik/<int:rocnik_pk>/startovka_export/<str:ordering_str>/',
        startovka_export,
        name='startovka_export'),
    path('rocnik/<int:rocnik_pk>/vysledky_export/',
        vysledky_export,
        name='vysledky_export'),
    path('rocnik/<int:rocnik_pk>/kategorie_export/',
        kategorie_export,
        name='kategorie_export'),

    path('kategorie/<int:kategorie_pk>/pdf/vysledkova_listina/',
        vysledky_kategorie_PDF,
        name='vysledky_kategorie_PDF'),
    path('rocnik/<int:rocnik_pk>/pdf/vysledkova_listina/',
        vysledky_rocnik_PDF,
        name='vysledky_rocnik_PDF'),
    path('kategorie/<int:kategorie_pk>/pdf/startovni_listina/',
        startovka_kategorie_PDF,
        name='startovka_kategorie_PDF'),
    path('rocnik/<int:rocnik_pk>/pdf/startovni_listina/',
        startovka_rocnik_PDF,
        name='startovka_rocnik_PDF'),

    # AUTOCOMPLETEs
    path('sport_autocomplete/', sport_autocomplete, name='sport_autocomplete'),
    path('zavod_autocomplete/', zavod_autocomplete, name='zavod_autocomplete'),
]

lide/models.py
from django.db import models
from django.db.models import Q
from django.utils.text import slugify
from django.urls import reverse


POHLAVI = (
    ('', '---'),
    ('m', 'muž'),
    ('z', 'žena'),
)


def _get_sorting_slug(slovo):

    """ Vrati upraveny sorting slug,
    napomaha razeni slov (jmena, nazvy klubu) s diakritikou.
    Nahradi pismena s diakritikou spojenim se Z
    """

    slovo = slovo.upper()
    vysledek = ''
    for pismeno in slovo:
        vysledek += pismeno
        if pismeno in 'ĚŠČŘŽÝÁÍÉŤĎŇÓÚŮÜÖËŁ':
            vysledek += 'Z'
    return slugify(vysledek)


class Clovek(models.Model):

    """ Clovek
    - clovek je pres Clenstvi spojen s Klubem
    - pres Zavodnika je spojen s Rocnikem a Kategorii
    """

    jmeno = models.CharField('Křestní jméno', max_length=20)
    prijmeni = models.CharField('Příjmení', max_length=30)
    pohlavi = models.CharField(
        'Pohlaví', max_length=1,
        choices=POHLAVI,
        null=True, blank=True)
    narozen = models.PositiveSmallIntegerField('Narozen(a)')
    jmeno_slug = models.SlugField(editable=False, unique=False, blank=True)
    prijmeni_slug = models.SlugField(editable=False, unique=False, blank=True)
    slug = models.SlugField(db_index=True, unique=True, blank=True)
    prijmeni_slug_sorting = models.SlugField(editable=False, unique=False)
    varovani = None


    class Meta:
        verbose_name = 'Člověk'
        verbose_name_plural = 'Lidé'
        ordering = ('prijmeni_slug_sorting', 'jmeno_slug')
        unique_together = ('jmeno', 'prijmeni', 'narozen')


    def __str__(self):
        return '{0} {1} {2}'.format(self.prijmeni, self.jmeno, self.narozen)


    def get_absolute_url(self, user=None):
        if user and user.is_active:
            return reverse('lide:clovek_update', args=(self.slug,))
        else:
            return reverse('lide:clovek_detail', args=(self.slug,))


    def save(self, *args, **kwargs):

        """
        Ulozeni cloveka
        - pohlavi: pokud neni nastaveno, tak ho odhadne z prijmeni
        - nastaveni vsech slugu
        """

        if not self.pohlavi:
            self.pohlavi = 'z' if self.prijmeni[-1] == 'á' else 'm'
        elif self.pohlavi not in POHLAVI:
            self.pohlavi = 'm' if self.pohlavi[0].lower() == 'm' else 'z'
        self.prijmeni_slug = slugify(self.prijmeni)
        self.prijmeni_slug_sorting = self.prijmeni_slug
        self.prijmeni_slug_sorting = _get_sorting_slug(self.prijmeni)
        self.jmeno_slug = slugify(self.jmeno)
        super(Clovek, self).save(*args, **kwargs)  # nejprve ulozi pro zjisteni ID
        self.slug = '{}-{}-{}_{}'.format(
            self.prijmeni_slug, self.jmeno_slug, str(self.narozen), str(self.id))
        return super(Clovek, self).save(update_fields=['slug']) #updatuje SLUG


    def cele_jmeno(self):
        return '{0} {1}'.format(self.prijmeni, self.jmeno)


    def serazene_clenstvi_pro_zavod(self, zavod):

        """ Vraci serazeny queryset clenstvi v klubech
        dle dulezitosti pro dany `Zavod`
        """

        vhodne_clenstvi = self.clenstvi.filter(
            Q(sport=zavod.sport) | Q(sport__isnull=True)
        ).order_by('-sport', '-priorita')
        if not vhodne_clenstvi:
            vhodne_clenstvi = self.clenstvi.all().order_by('-priorita')
        return vhodne_clenstvi


    def jednotlive_kluby(self):

        """ Vrati set Klubu cloveka """

        from kluby.models import Klub
        return set(Klub.objects.filter(clenstvi__clovek=self))


class Clenstvi(models.Model):

    """ Clenstvi
    - propojeni cloveka, klubu a sportu,
    - mezi clovekem a klubem je vztah m2m
    - Clenstvi je pouzito pouze pro nabidnuti klubu u vkladani zavodnika, neni na nej nic natvrdo navazano
    """

    clovek = models.ForeignKey(
        'Clovek',
        verbose_name='člověk', related_name='clenstvi',
        on_delete=models.CASCADE)
    klub = models.ForeignKey(
        'kluby.Klub',
        verbose_name='klub', related_name='clenstvi',
        on_delete=models.CASCADE)
    sport = models.ForeignKey(
        'zavody.Sport',
        on_delete=models.SET_NULL,
        null=True, blank=True)
    priorita = models.SmallIntegerField(
        'Priorita', null=True, blank=True,
        help_text='určuje prioritu klubů se stejným sportem - větší číslo vyhrává !')

    class Meta:
        verbose_name = 'Členství v klubu'
        verbose_name_plural = 'Členství v klubech'
        ordering = ('clovek', '-sport', '-priorita')
        unique_together = ('clovek', 'klub', 'sport')


    def __str__(self):
        return '{0} - {1}'.format(self.clovek, self.klub)

lide/forms.py
from django import forms
from django.core.exceptions import MultipleObjectsReturned
from django.db import transaction
from django.db.models import Q, Count

from .models import Clovek, Clenstvi
from kluby.models import Klub
from .functions import zavodnici_import_clean_csv
from zavody.models import Zavodnik


class ClovekUpdateForm(forms.ModelForm):
    smazat = forms.BooleanField(
        label='Smazat člověka',
        required=False)
    presunout_vysledky = forms.ModelChoiceField(
        label='Výsledky přesunout na jiného člověka',
        required=False,
        queryset=Clovek.objects.all(),
        help_text='Výsledky lze přesunout na jiného člověka i bez smazání původního člověka.',
        widget=forms.Select(attrs={'class': 'dropdown search'}))

    class Meta:
        model = Clovek
        fields = ('prijmeni', 'jmeno', 'pohlavi', 'narozen')


    def __init__(self, *arg, **kwargs):
        super().__init__(*arg, **kwargs)
        self.fields['presunout_vysledky'].queryset = Clovek.objects.exclude(pk=self.instance.pk)

    def save(self, *args, **kwargs):
        '''-prevadi vysledky na noveho cloveka
        - maze aktualniho cloveka
        - vytvari zpravy pro `messages`'''
        data = self.cleaned_data
        zpravy = []
        clovek = None
        if data['presunout_vysledky']:
            clovek = data['presunout_vysledky']
            Zavodnik.objects.filter(clovek=self.instance).update(clovek=clovek)
            zpravy.append(
                "Výsledky přesunuty z člověka '{0}'' na '{1}'".format(self.instance, clovek))

        if data['smazat']:
            zpravy.append("Člověk '{0}' smazán".format(self.instance))
            self.instance.delete()
            smazan = True
        else:
            clovek = super().save(*args, **kwargs)
            zpravy.append('změny v člověku uloženy')
            smazan = False

        return (clovek, zpravy, smazan)


class CSVsouborFormular(forms.Form):
    soubor = forms.FileField(
        label='soubor *.csv',
        required=True,
        widget=forms.FileInput(attrs={'accept': '.csv'}))


class LideImportCSVForm(forms.Form):
    soubor = forms.FileField(
        label='soubor *.csv',
        required=True,
        widget=forms.FileInput(attrs={'accept': '.csv'}))

    def clean_soubor(self):
        radky, chyby = zavodnici_import_clean_csv(self.cleaned_data['soubor'])
        if chyby:
            raise forms.ValidationError(chyby)
        else:
            return radky

    @transaction.atomic
    def save(self):
        lide = []
        radky = self.cleaned_data['soubor']
        for radek in radky:
            try:
                clovek, novy_clovek = Clovek.objects.get_or_create(
                    slug__startswith=radek['slug'],
                    defaults=radek['defaults'])
            except MultipleObjectsReturned:
                # v případě nalezení vícero Človků, přiřadí vybere Člověk s větším počtem účasti v Ročník
                clovek = (
                    Clovek.objects
                    .filter(slug__startswith=radek['slug'])
                    .annotate(pocet_zavodu=Count('zavodnici'))
                    .order_by('-pocet_zavodu').first())
                novy_clovek = False

            if any([radek['klub_nazev'], radek['klub_zkratka'], radek['klub_id']]):

                # pokusi se najit klub dle nenulovych hodnot: klub_nazev, klub_zkratka, klub_id
                klub = Klub.objects.filter(
                    Q(nazev=radek['klub_nazev']) if radek['klub_nazev'] else Q() |
                    Q(zkratka=radek['klub_zkratka']) if radek['klub_zkratka'] else Q() |
                    Q(klub_id=radek['klub_id']) if radek['klub_id'] else Q()
                ).first()
                novy_klub = False

                # pokud nenajde, pokusi se Klub vytvorit
                if not klub:
                    klub = Klub.objects.create(
                        # do nazev dosadi prvni nenulovou hodnotu z klub_nazev, klub_zkratka, klub_id
                        nazev=radek['klub_nazev'] or radek['klub_zkratka'] or radek['klub_id'],
                        zkratka=radek['klub_zkratka'],
                        klub_id=radek['klub_id'] or None)
                    novy_klub = True

                if not Clenstvi.objects.filter(clovek=clovek, klub=klub).exists():
                    Clenstvi.objects.create(
                        clovek=clovek,
                        klub=klub)
            else:
                klub = None
                novy_klub = None
            lide.append(
                (clovek, klub, novy_clovek, novy_klub, radek))
        return lide

templates/lide/clovek_detail.html
{% extends 'base.html' %}
{% load l10n custom_filters %}

{% block title %}
    ČLOVĚK | {{ clovek }}
{% endblock title %}

{% block section %}section_lide{% endblock section %}

{% block breadcrumb %}
    <div class="ui breadcrumb">
        <a href="{% url 'lide:lide_list' %}#{{ clovek.prijmeni.0 }}" class="section">lidé</a>
        <i class="right chevron icon divider"></i>
        <div class="active section">detail člověka</div>
    </div>
{% endblock breadcrumb %}

{% block header %}
    <h1 class="ui header">
        {% if referer %}
            <a href="{{ referer }}" title="zpět na předchozí stránku">
                <i class="ui reply mail link big icon"></i>
            </a>
        {% else %}
            <a href="{% url 'lide:lide_list' %}#{{ clovek.prijmeni.0 }}" title="zpět na seznam lidí">
                <i class="ui reply mail link big icon"></i>
            </a>
        {% endif %}
        <div class="content">
            <i class="ui user big icon"></i>
            {{ clovek.cele_jmeno }}
            {% if user.is_staff %}
                <a href="{% url 'admin:lide_clovek_change' clovek.id %}" title="editovat člověka" target="_blank" class="ui icon button">
                    <i class="settings link icon"></i>
                </a>
            {% endif %}
            <div class="sub header">detail človeka</div>
        </div>
    </h1>
{% endblock header %}

{% block content %}
    <div class="ui stackable grid">

        <div class="sixteen wide tablet five wide computer column">
            <dl class="vlastnosti">
                <dt>Příjmení</dt>
                <dd>{{ clovek.prijmeni }}</dd>
                <dt>Jméno</dt>
                <dd>{{ clovek.jmeno }}</dd>
                <dt>Pohlaví</dt>
                <dd>{{ clovek.get_pohlavi_display }}</dd>
                <dt>Narozen{% if clovek.pohlavi == 'z' %}a{% endif %}</dt>
                <dd>{{ clovek.narozen|unlocalize }}</dd>
                <dt>Kluby</dt>
                <dd>
                    {% with clovek.jednotlive_kluby as kluby %}
                        {% if kluby %}
                            <ul>
                                {% for klub in kluby %}
                                    <li>
                                        <a href="{% url 'kluby:klub_detail' klub.slug %}" title="na detail klubu">
                                            {{ klub }}
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>
                        {% else %}
                            -
                        {% endif %}
                    {% endwith %}
                </dd>
                {% if jmenovci %}
                    <dt>
                        Jmenovci
                    </dt>
                    <dd>
                        <ul>
                            {% for jmenovec in jmenovci %}
                                <li>
                                    <a href="{{ jmenovec.get_absolute_url }}">
                                        {{ jmenovec }}
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </dd>
                {% endif %}
            </dl>
        </div>

        <div class="sixteen wide tablet eleven wide computer column">
            <table class="ui unstackable celled structured table">
                <thead>
                    <tr>
                        <th colspan="5">zúčastněné závody</th>
                        <th colspan="4" class="center aligned">umístění v závodu</th>
                    </tr>
                    <tr>
                        <th rowspan="2" class="center aligned">ročník</th>
                        <th rowspan="2" class="center aligned">závod</th>
                        <th rowspan="2" class="center aligned">kategorie</th>
                        <th rowspan="2" class="center aligned">trať</th>
                        <th rowspan="2" class="center aligned">výsledný čas</th>
                        <th colspan="2" class="center aligned">v kategorii</th>
                        <th colspan="2" class="center aligned">na trati</th>
                    </tr>
                    <tr>
                        <th class="right aligned">umístění</th>
                        <th class="right aligned" title="celkem závodníků v kategorii">Σ</th>
                        <th class="right aligned">umístění</th>
                        <th class="right aligned" title="celkem závodníků na trati">Σ</th>
                    </tr>
                </thead>
                <tbody>
                    {% regroup zavodnici|dictsortreversed:'rocnik.datum' by rocnik.datum|date:'Y' as roky_list %}
                    {% for rok in roky_list %}
                        {% for zavodnik in rok.list %}
                            <tr>
                                {% if forloop.first %}
                                    <td rowspan="{{ rok.list|length }}" class="center aligned">
                                        {{ rok.grouper }}
                                    </td>
                                {% endif %}
                                <td>
                                    <a href="{% url 'zavody:vysledkova_listina' zavodnik.rocnik.id %}#zavodnik_{{ zavodnik.id|safe }}" title="{{ zavodnik.rocnik.datum }} - na výsledkovou listinu závodu">
                                        {{ zavodnik.rocnik.zavod.nazev }}
                                    </a>
                                </td>
                                <td>
                                    {{ zavodnik.kategorie_temp.nazev }}
                                </td>
                                <td>
                                    {{ zavodnik.kategorie_temp.delka_trate }}
                                </td>
                                <td>
                                    {{ zavodnik.vysledny_cas|desetiny_sekundy|default:'' }}
                                </td>
                                <td class="right aligned">
                                    {{ zavodnik.poradi_v_kategorii|default:'' }}
                                </td>
                                <td class="right aligned">
                                    {{ zavodnik.kategorie_temp.zavodnici_temp.count }}
                                </td>
                                <td class="right aligned">
                                    {{ zavodnik.poradi_na_trati|default:'' }}
                                </td>
                                <td class="right aligned">
                                    {% if zavodnik.zavodniku_na_trati %}
                                        {{ zavodnik.zavodniku_na_trati|default:'' }}
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}

                    {% empty %}
                        <tr>
                            <td colspan="9" class="center aligned">
                                žádný závod
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock content %}

templates/lide/clovek_list.html
{% extends 'base.html' %}
{% load l10n custom_filters %}

{% block title %}
    LIDÉ | přehled
{% endblock title %}

{% block section %}section_lide{% endblock section %}

{% block header %}
    <h1 class="ui header">
        <i class="ui user big icon"></i>
        <div class="content">
            Lidé
            <div class="sub header">přehled {{ lide|length }} registrovaných lidí</div>
        </div>
    </h1>
{% endblock header %}

{% block staff %}
    {% if user.is_staff %}
        <div class="ui stacked secondary segment noprint">
            <a href="{% url 'lide:import_csv' %}" class="ui blue icon button">
                <i class="plus link icon"></i>
                import lidí
            </a>
        </div>
    {% endif %}
{% endblock staff %}

{% block content %}
    {% regroup lide by prijmeni_slug.0 as lide_abc %}
    <div class="ui divided relaxed horizontal list">
        {% for pismeno in lide_abc %}
            <a href=".#{{ pismeno.grouper }}" class="item">
                {{ pismeno.grouper|upper }}
            </a>
        {% endfor %}
    </div>

    <table class="ui celled unstackable table">
        <thead>
            <tr>
                <th>příjmení</th>
                <th>jméno</th>
                <th>narozen(a)</th>
                <th>klub(y)</th>
                <th>startů</th>
            </tr>
        </thead>
        <tbody>
            {% for pismeno in lide_abc %}
                <tr id="{{ pismeno.grouper|default:'bez příjmení' }}">
                    <td colspan="5">
                        <h2>{{ pismeno.grouper|upper }}</h2>
                    </td>
                </tr>
                {% for clovek in pismeno.list %}
                    <tr>
                        <td>
                            <a href="{% detail_url clovek %}" title="detail člověka">
                                {{ clovek.prijmeni }}
                            </a>
                        </td>
                        <td>
                            {% if user.is_staff %}
                                <a href="{% url 'admin:lide_clovek_change' clovek.id %}" title="editovat člověka v adminitraci" target="_blank">
                                    <i class="settings link icon"></i>
                                </a>
                            {% endif %}
                            {{ clovek.jmeno }}
                        </td>
                        <td>
                            {{ clovek.narozen|unlocalize }}
                        </td>
                        <td>
                            <div class="ui divided relaxed horizontal list">
                                {% for klub in clovek.jednotlive_kluby %}
                                    <div class="item">
                                        {{ klub }}
                                    </div>
                                {% endfor %}
                            </div>
                        </td>
                        <td class="right aligned">
                            {{ clovek.pocet_zavodu|default:'' }}
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan=4>
                            žádný člověk
                        </td>
                    </tr>
                {% endfor %}
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

templates/lide/klub_detail.html
{% extends 'base.html' %}
{% load l10n custom_filters %}

{% block title %}
    KLUB | {{ klub.nazev }}
{% endblock title %}

{% block section %}section_kluby{% endblock section %}

{% block breadcrumb %}
    <div class="ui breadcrumb">
        <a href="{% url 'kluby:kluby_list' %}#{{ klub.nazev.0 }}" class="section">kluby</a>
        <i class="right chevron icon divider"></i>
        <div class="active section">detail klubu</div>
    </div>
{% endblock breadcrumb %}

{% block header %}
    <h1 class="ui header">
        {% if referer %}
            <a href="{{ referer }}" title="zpět na předchozí stránku">
                <i class="ui reply mail link big icon"></i>
            </a>
        {% else %}
            <a href="{% url 'kluby:kluby_list' %}#{{ klub.nazev.0 }}" title="zpět na seznam klubů">
                <i class="ui reply mail link big icon"></i>
            </a>
        {% endif %}

        <div class="content">
            <i class="ui users big icon"></i>
            {{ klub.nazev }}
            {% if user.is_staff %}
                <a href="{% url 'kluby:klub_update' klub.slug %}" title="editovat klub" class="ui icon button">
                    <i class="edit link icon"></i>
                </a>
                <a href="{% url 'admin:kluby_klub_change' klub.id %}" title="editovat klub v administraci" target="_blank" class="ui icon button">
                    <i class="settings link icon"></i>
                </a>
            {% endif %}
            <div class="sub header">detail klubu</div>
        </div>
    </h1>
{% endblock header %}

{% block content %}
    <div class="ui stackable grid">
        <div class="sixteen wide tablet ten wide computer column">
            <dl class="vlastnosti">
                <dt>Název</dt>
                <dd>{{ klub.nazev }}</dd>
                <dt>Sport</dt>
                <dd>{{ klub.sport|default:'-' }}</dd>
                {% if klub.info %}
                    <dt>Info</dt>
                    <dd>{{ klub.info|safe|urlize|linebreaks }}</dd>
                {% endif %}
            </dl>
        </div>

        <div class="sixteen wide tablet six wide computer column">
            <table class="ui unstackable celled compact small table">
                <thead>
                    <tr>
                        <th colspan="3">
                            celkem {{ clenove|length }}  závodníků
                        </th>
                    </tr>
                    <tr>
                        <th>příjmení</th>
                        <th>jméno</th>
                        <th>narozen(a)</th>
                    </tr>
                </thead>
                <tbody>
                    {% for clovek in clenove %}
                        <tr>
                            <td>
                                <a href="{% detail_url clovek %}" title="na detail člověka">
                                    {{ clovek.prijmeni }}
                                </a>
                            </td>
                            <td>
                                {{ clovek.jmeno }}
                            </td>
                            <td>
                                {{ clovek.narozen|unlocalize }}
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan=3>
                                žádný závodník
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock content %}