hanes/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    path('zavody/',
        include('zavody.urls', namespace='zavody')),
    path('lide/',
        include('lide.urls', namespace='lide')),
    path('kluby/',
        include('kluby.urls', namespace='kluby')),
    path('zavodnici/',
        include('zavodnici.urls', namespace='zavodnici')),
    path('pohary/',
        include('pohary.urls', namespace='pohary')),

    path('zalohovat_databazi/',
        login_required(views.backup_database), name='backup_database'),
    path('flatpages/editace/<int:pk>/',
        login_required(views.FlatPageUpdate.as_view()), name='flatpage_editace'),
    path('',
        views.uvod, {'url': '/uvod/'}, name='uvod'),

    # django
    path('admin/', admin.site.urls),
    path('accounts/',
        include('django.contrib.auth.urls')),
]

if settings.TEMPLATE_DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

lide/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import *

app_name='lide'
urlpatterns = [
    # LISTs
    path('',
        clovek_list, name='lide_list'),

    # DETAILs
    path('detail/<str:slug>/',
        ClovekDetailView.as_view(), name='clovek_detail'),
    path('editace/<str:slug>/',
        login_required(clovek_update), name='clovek_update'),

    # IMPORTs
    path('import_csv/',
        LideImportCSV.as_view(), name='import_csv'),

    # AUTOCOMPLETEs
    path('clovek_autocomplete/',
        clovek_autocomplete, name='clovek_autocomplete'),
    path('rocnik/<int:rocnik_pk>/clovek_autocomplete/',
        clovek_autocomplete, name='clovek_autocomplete'),

    # UTILITY
    path('duplicity/',
        duplicity, name='duplicity'),
]

pohary/urls.py
from django.urls import path
from . import views


app_name = 'pohary'
urlpatterns = [
    # LISTs
    path('',
        views.PoharyListView.as_view(),
        name='pohary_list'),

    # DETAILs
    path('detail/<str:slug>/',
        views.PoharDetailView.as_view(),
        name='pohar_detail'),
    path('kategorie/<int:pk>/',
        views.KategoriePoharuDetailView.as_view(),
        name='kategorie-poharu_detail'),
    path('pridat/',
        views.PoharCreateView.as_view(),
        name='pohar_create'),
]

zavody/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required

from .views import *

app_name='zavody'
urlpatterns = [
    # LISTs
    path('',
        ZavodyListView.as_view(),
        name='zavody_list'),

    # DETAILs
    path('detail/<int:pk>/',
        ZavodDetailView.as_view(),
        name='zavod_detail'),
    path('rocnik/<int:pk>/detail/',
        RocnikDetailView.as_view(),
        name='rocnik_detail'),
    path('rocnik/<int:pk>/startovne/',
        StartovneRocnikuDetailView.as_view(),
        name='startovne_rocniku_detail'),
    path('kategorie/<int:pk>/',
        KategorieDetailView.as_view(),
        name='kategorie_detail'),
    path('rocnik/<int:rocnik_pk>/vysledkova_listina/',
        vysledkova_listina,
        name='vysledkova_listina'),
    path('rocnik/<int:pk>/startovni_casy/',
        login_required(StartovniCasyView.as_view()),
        name='startovni_casy'),

    # CREATEs
    path('zavod/novy/',
        ZavodPridejView.as_view(),
        name='zavod_pridani'),
    path('<str:slug>/rocnik/novy/',
        RocnikPridejView.as_view(),
        name='rocnik_pridani'),

    # UPDATEs
    path('rozkategorizovat_zavodniky/<int:rocnik_pk>/',
        login_required(rozkategorizovat_zavodniky),
        name='rozkategorizovat_zavodniky'),
    path('formular_startera/<int:rocnik_pk>/',
        login_required(formular_startera),
        name='formular_startera'),
    path('zavod/<int:pk>/editace/',
        ZavodUpdateView.as_view(),
        name='zavod_editace'),
    path('rocnik/<int:pk>/editace/',
        RocnikUpdateView.as_view(),
        name='rocnik_editace'),
    path('kategorie/<int:pk>/editace/',
        KategorieUpdateView.as_view(),
        name='kategorie_editace'),

    # DELETE
    path('rocnik/<int:pk>/smazat/',
        RocnikDeleteView.as_view(),
        name='rocnik_smazani'),
    path('zavod/<int:pk>/smazat/',
        ZavodDeleteView.as_view(),
        name='zavod_smazani'),
    # path('kategorie/<int:pk>/smazat/',
    #     KategorieDeleteView.as_view(),
    #     name='kategorie_smazani'),

    # FORMs
    path('pridani_zavodniku/rocnik/<int:pk>/',
        login_required(pridani_zavodniku),
        name='pridani_zavodniku'),
    path('import_zavodniku/rocnik/<int:pk>/',
        login_required(ImportZavodnikuView.as_view()),
        name='import_zavodniku'),
    path('rocnik/<int:rocnik_pk>/startovni_listina/',
        startovni_listina,
        name='startovni_listina'),
    path('rocnik/<int:rocnik_pk>/startovni_listina/<str:ordering_str>/',
        startovni_listina,
        name='startovni_listina'),
    path('rocnik/<int:rocnik_pk>/cilovy_formular/',
        login_required(cilovy_formular),
        name='cilovy_formular'),
    path('rocnik/<int:rocnik_pk>/import_souboru_casu/txt/',
        login_required(ImportCasuSouborView.as_view()),
        name='import_souboru_casu_txt'),
    path('rocnik/<int:rocnik_pk>/import_textu_casu/',
        login_required(ImportCasuTextView.as_view()),
        name='import_textu_casu'),
    path('rocnik/<int:rocnik_pk>/zpracovani_importovanych_casu/txt/',
        login_required(ZpracovaniImportovanychCasuTxtView.as_view()),
        name='zpracovani_importovanych_casu_txt'),

    # AJAX
    path('kategorie/<int:pk>/startovni_casy/upravit/',
        login_required(AjaxKategorieStartovniCasyUpdateView.as_view()),
        name='ajax_kategorie_startovni_casy_update'),

    # EXPORT
    path('rocnik/<int:rocnik_pk>/startovka_export/',
        startovka_export,
        name='startovka_export'),
    path('rocnik/<int:rocnik_pk>/startovka_export/<str:ordering_str>/',
        startovka_export,
        name='startovka_export'),
    path('rocnik/<int:rocnik_pk>/vysledky_export/',
        vysledky_export,
        name='vysledky_export'),
    path('rocnik/<int:rocnik_pk>/kategorie_export/',
        kategorie_export,
        name='kategorie_export'),

    path('kategorie/<int:kategorie_pk>/pdf/vysledkova_listina/',
        vysledky_kategorie_PDF,
        name='vysledky_kategorie_PDF'),
    path('rocnik/<int:rocnik_pk>/pdf/vysledkova_listina/',
        vysledky_rocnik_PDF,
        name='vysledky_rocnik_PDF'),
    path('kategorie/<int:kategorie_pk>/pdf/startovni_listina/',
        startovka_kategorie_PDF,
        name='startovka_kategorie_PDF'),
    path('rocnik/<int:rocnik_pk>/pdf/startovni_listina/',
        startovka_rocnik_PDF,
        name='startovka_rocnik_PDF'),

    # AUTOCOMPLETEs
    path('sport_autocomplete/', sport_autocomplete, name='sport_autocomplete'),
    path('zavod_autocomplete/', zavod_autocomplete, name='zavod_autocomplete'),
]

lide/models.py
from django.db import models
from django.db.models import Q
from django.utils.text import slugify
from django.urls import reverse


POHLAVI = (
    ('', '---'),
    ('m', 'muž'),
    ('z', 'žena'),
)


def _get_sorting_slug(slovo):

    """ Vrati upraveny sorting slug,
    napomaha razeni slov (jmena, nazvy klubu) s diakritikou.
    Nahradi pismena s diakritikou spojenim se Z
    """

    slovo = slovo.upper()
    vysledek = ''
    for pismeno in slovo:
        vysledek += pismeno
        if pismeno in 'ĚŠČŘŽÝÁÍÉŤĎŇÓÚŮÜÖËŁ':
            vysledek += 'Z'
    return slugify(vysledek)


class Clovek(models.Model):

    """ Clovek
    - clovek je pres Clenstvi spojen s Klubem
    - pres Zavodnika je spojen s Rocnikem a Kategorii
    """

    jmeno = models.CharField('Křestní jméno', max_length=20)
    prijmeni = models.CharField('Příjmení', max_length=30)
    pohlavi = models.CharField(
        'Pohlaví', max_length=1,
        choices=POHLAVI,
        null=True, blank=True)
    narozen = models.PositiveSmallIntegerField('Narozen(a)')
    jmeno_slug = models.SlugField(editable=False, unique=False, blank=True)
    prijmeni_slug = models.SlugField(editable=False, unique=False, blank=True)
    slug = models.SlugField(db_index=True, unique=True, blank=True)
    prijmeni_slug_sorting = models.SlugField(editable=False, unique=False)
    varovani = None


    class Meta:
        verbose_name = 'Člověk'
        verbose_name_plural = 'Lidé'
        ordering = ('prijmeni_slug_sorting', 'jmeno_slug')
        unique_together = ('jmeno', 'prijmeni', 'narozen')


    def __str__(self):
        return '{0} {1} {2}'.format(self.prijmeni, self.jmeno, self.narozen)


    def get_absolute_url(self, user=None):
        if user and user.is_active:
            return reverse('lide:clovek_update', args=(self.slug,))
        else:
            return reverse('lide:clovek_detail', args=(self.slug,))


    def save(self, *args, **kwargs):

        """
        Ulozeni cloveka
        - pohlavi: pokud neni nastaveno, tak ho odhadne z prijmeni
        - nastaveni vsech slugu
        """

        if not self.pohlavi:
            self.pohlavi = 'z' if self.prijmeni[-1] == 'á' else 'm'
        elif self.pohlavi not in POHLAVI:
            self.pohlavi = 'm' if self.pohlavi[0].lower() == 'm' else 'z'
        self.prijmeni_slug = slugify(self.prijmeni)
        self.prijmeni_slug_sorting = self.prijmeni_slug
        self.prijmeni_slug_sorting = _get_sorting_slug(self.prijmeni)
        self.jmeno_slug = slugify(self.jmeno)
        super(Clovek, self).save(*args, **kwargs)  # nejprve ulozi pro zjisteni ID
        self.slug = '{}-{}-{}_{}'.format(
            self.prijmeni_slug, self.jmeno_slug, str(self.narozen), str(self.id))
        return super(Clovek, self).save(update_fields=['slug']) #updatuje SLUG


    def cele_jmeno(self):
        return '{0} {1}'.format(self.prijmeni, self.jmeno)


    def serazene_clenstvi_pro_zavod(self, zavod):

        """ Vraci serazeny queryset clenstvi v klubech
        dle dulezitosti pro dany `Zavod`
        """

        vhodne_clenstvi = self.clenstvi.filter(
            Q(sport=zavod.sport) | Q(sport__isnull=True)
        ).order_by('-sport', '-priorita')
        if not vhodne_clenstvi:
            vhodne_clenstvi = self.clenstvi.all().order_by('-priorita')
        return vhodne_clenstvi


    def jednotlive_kluby(self):

        """ Vrati set Klubu cloveka """

        from kluby.models import Klub
        return set(Klub.objects.filter(clenstvi__clovek=self))


class Clenstvi(models.Model):

    """ Clenstvi
    - propojeni cloveka, klubu a sportu,
    - mezi clovekem a klubem je vztah m2m
    - Clenstvi je pouzito pouze pro nabidnuti klubu u vkladani zavodnika, neni na nej nic natvrdo navazano
    """

    clovek = models.ForeignKey(
        'Clovek',
        verbose_name='člověk', related_name='clenstvi',
        on_delete=models.CASCADE)
    klub = models.ForeignKey(
        'kluby.Klub',
        verbose_name='klub', related_name='clenstvi',
        on_delete=models.CASCADE)
    sport = models.ForeignKey(
        'zavody.Sport',
        on_delete=models.SET_NULL,
        null=True, blank=True)
    priorita = models.SmallIntegerField(
        'Priorita', null=True, blank=True,
        help_text='určuje prioritu klubů se stejným sportem - větší číslo vyhrává !')

    class Meta:
        verbose_name = 'Členství v klubu'
        verbose_name_plural = 'Členství v klubech'
        ordering = ('clovek', '-sport', '-priorita')
        unique_together = ('clovek', 'klub', 'sport')


    def __str__(self):
        return '{0} - {1}'.format(self.clovek, self.klub)

pohary/forms.py
from django import forms

from .models import Pohar


class PoharCreateForm(forms.ModelForm):
    kopirovat_kategorie = forms.BooleanField(
        label='Kopírovat kategorie z prvního závodu?', initial=True, required=False)

    class Meta:
        model = Pohar
        fields = '__all__'

pohary/views.py
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic import CreateView, DetailView, ListView
from io import BytesIO

from zavody.pdf import PdfPrint
from zavody.views import TITLE_TEMPLATE
from zavodnici.views import desetiny_sekundy

from .forms import PoharCreateForm
from .models import KategoriePoharu, Pohar


class PoharyListView(ListView):
    model = Pohar
    template_name = 'pohary/pohar_list.html'


class PoharDetailView(DetailView):
    model = Pohar
    template_name = 'pohary/pohar_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        pohar = self.object
        zavodnici = pohar.zavodnici_vsichni()
        context['rocniky'] = []
        context['kluby'] = []

        for rocnik in pohar.rocniky.all():
            zavodniku = zavodnici.filter(rocnik=rocnik).count()
            context['rocniky'].append((rocnik, zavodniku))

        for klub in pohar.kluby.all():
            zavodniku = zavodnici.filter(klub=klub).count()
            context['kluby'].append((klub, zavodniku))

        return context


class KategoriePoharuDetailView(DetailView):
    model = KategoriePoharu
    context_object_name = 'kategorie'
    template_name = 'pohary/kategoriepoharu_detail.html'

    def get_context_data(self, **kwargs):
        context = super(KategoriePoharuDetailView, self).get_context_data(**kwargs)
        context['pohar'] = self.object.pohar
        return context


class PoharCreateView(CreateView):
    form_class = PoharCreateForm
    template_name = 'pohary/pohar_create.html'
    success_url = reverse_lazy('pohary:pohary_list')

    def get_context_data(self, **kwargs):
        context = super(PoharCreateView, self).get_context_data(**kwargs)
        context['pohary'] = Pohar.objects.all()
        return context

    def form_valid(self, form):
        "nakopirovani hodnot kategorii z prvniho zavodu"
        pohar = form.save()
        if form.cleaned_data['kopirovat_kategorie']:
            rocnik = pohar.rocniky.first()
            for values in list(rocnik.kategorie.all().values()):
                del values['id']
                del values['delka_trate']
                del values['rocnik_id']
                del values['spusteni_stopek']
                del values['startovne']
                values['pohar'] = pohar
                KategoriePoharu.objects.create(**values)
        return HttpResponseRedirect(
            pohar.get_absolute_url())


def vysledky_kategorie_pdf(request, kategorie_pk):

    from zavody.templatetags import custom_filters

    kategorie = KategoriePoharu.objects.get(pk=kategorie_pk)
    rows = []
    widths = [1.5, 1.5, 3, 2.7, 1.5, 6, 2.3, 1.5]
    for zavodnik in kategorie.serazeni_zavodnici(razeni=None):
        rows.append([
                zavodnik.poradi_v_kategorii() or '',
                zavodnik.cislo or '',
                zavodnik.clovek.prijmeni,
                zavodnik.clovek.jmeno,
                zavodnik.clovek.narozen,
                zavodnik.klub.nazev if zavodnik.klub else '',
                zavodnik.nedokoncil or desetiny_sekundy(zavodnik.vysledny_cas),
                zavodnik.poradi_na_trati() or ''
            ])
    pdf_print = PdfPrint(BytesIO())
    pdf = pdf_print.sheet(
        [{
            'title': TITLE_TEMPLATE.format(
                kategorie,
                custom_filters.rozsah_narozeni(kategorie.rozsah_narozeni())
            ),
            'headers': (['pořadí', 'číslo', 'příjmení', 'jméno', 'nar.', 'klub', 'výsledný čas', 'na trati'],),
            'rows': rows}],
        widths)
    return HttpResponse(pdf, content_type='application/pdf')

templates/pohary/pohar_create.html
{% extends 'base.html' %}
{% load l10n %}

{% block title %}
    PŘIDÁNÍ POHÁRŮ
{% endblock title %}

{% block section %}section_pohary{% endblock %}

{% block custom_js %}
    {% comment %}
    <script type="text/javascript">
        $(document).ready(function(){
            $("#id_sport").devbridgeAutocomplete({
                serviceUrl: "{% url 'pohary:sport_autocomplete' %}",
                minChars: 1,
                deferRequestBy: 0,
                maxHeight: 600,
                preventBadQueries: false,
                triggerSelectOnValidInput: false,
                noCache: false,
                width: 300,
            });
        });
    </script>
    {% endcomment %}
{% endblock %}

{% block header %}
    <h1 class="ui header">
        <div class="content">
            <i class="trophy big icon"></i>
            Přidání poháru
        </div>
    </h1>    
{% endblock header %}

{% block staff %}
{% endblock staff %}

{% block content %}
    <div class="ui grid">
        <div class="ui ten wide column">
            <h3>Přidání nového poháru</h3>
            <form action="" method="POST" class="ui form">
                {% csrf_token %}
                {% for field in form %}
                    {% include "elements/_form_error_field.html" with label=True required=True %}
                {% endfor %}
                <button type="submit" class="ui primary icon button">
                    <i class="save icon"></i>
                    odeslat
                </button>        
                <a href="{% url 'pohary:pohary_list' %}" title="neuložit a zpět na seznam pohárů" class="ui icon button">
                    <i class="ui reply mail icon"></i>
                    zrušit
                </a>
            </form>            
        </div>
        <div class="ui six wide column">
            <h3>Seznam již registrovných pohárů</h3>
            <table class="ui celled unstackable collapsing table">
                <thead>
                    <tr>
                        <th>název</th>
                        <th>datum</th>
                    </tr>
                </thead>
                <tbody>
                    {% for pohar in pohary %}
                        <tr>
                            <td>
                                <a href="{{ pohar.get_absolute_url }}">
                                    {{ pohar.nazev }}
                                </a>
                            </td>
                            <td>
                                {{ pohar.datum }}
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan=2>
                                žádný pohár
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock content %}

templates/pohary/pohar_detail.html
{% extends 'base.html' %}
{% load l10n %}

{% block title %}
    POHÁR | {{ pohar.nazev }}
{% endblock title %}

{% block section %}section_pohary{% endblock section %}

{% block breadcrumb %}
    <div class="ui breadcrumb">
        <a href="{% url 'pohary:pohary_list' %}" class="section">poháry</a>
        <i class="right chevron icon divider"></i>
        <div class="active section">detail poháru</div>
    </div>
{% endblock breadcrumb %}

{% block header %}
    <h1 class="ui header">
        <a href="{% url 'pohary:pohary_list' %}" title="na seznam pohárů">
            <i class="ui reply mail link big icon"></i>
        </a>
        <div class="content">
            <i class="ui trophy big icon"></i>
            {{ pohar }}
            <div class="sub header">detail poháru</div>
        </div>
    </h1>
{% endblock header %}

{% block staff %}
    <div class="ui stacked secondary segment noprint">
    {% comment %}
        {% if user.is_active %}
            <a href="{% url 'pohary:rocnik_pridani' pohar.slug %}" class="ui blue icon button">
                <i class="plus icon"></i>
                nový ročník
            </a>
            <a href="{% url 'pohary:pohar_editace' pohar.id %}" class="ui black icon button">
                <i class="edit icon"></i>
                editace poháru
            </a>
        {% endif %}
    {% endcomment %}
        {% if user.is_staff %}
            <a href="{% url 'admin:pohary_pohar_change' pohar.id %}" title="editovat pohár v administraci" target="_blank" class="ui icon black button">
                <i class="settings icon"></i>
                admin poháru
            </a>
        {% endif %}
    </div>
{% endblock staff %}

{% block content %}
    <h3>Závody</h3>
    <table class="ui celled definition collapsing large table">
        <thead class="full-width">
            <tr>
                <th>ročník</th>
                <th>závodníků celkem</th>
                <th>závodníků v pohárů</th>
            </tr>
        </thead>
        <tbody>
            {% for rocnik, zavodniku in rocniky %}
                <tr>
                    <td>
                        <a href="{{ rocnik.get_absolute_url }}">
                            {{ rocnik }}
                        </a>
                    </td>
                    <td>
                        {{ rocnik.zavodnici.count }}
                    </td>
                    <td>
                        {{ zavodniku }}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <h3>Kategorie poháru</h3>
    <table class="ui celled table">
        <thead>
            <tr>
                <th>značka</th>
                <th>název kategorie</th>
                <th>pohlaví</th>
                <th>věk</th>
                <th>závodníků</th>
            </tr>
        </thead>
        <tbody>
            {% for kategorie in pohar.kategorie_poharu.all %}
                <tr>
                    <td>
                        {{ kategorie.znacka }}
                    </td>
                    <td>
                        <a href="{{ kategorie.get_absolute_url }}">
                            {{ kategorie.nazev }}
                        </a>
                    </td>
                    <td>
                        {{ kategorie.get_pohlavi_display|default:'unisex' }}
                    </td>
                    <td title="narozeni v rozmezí: {{ kategorie.rozsah_narozeni.0|unlocalize }} - {{ kategorie.rozsah_narozeni.1|unlocalize }}">
                        {{ kategorie.vek_od|default:0 }} - {{ kategorie.vek_do|default:'starší' }}
                    </td>
                    <td>
                        {{ kategorie.zavodnici|length }}
                    </td>
                </tr>
            {% endfor %}
            {% with pohar.zavodnici_bez_kategorie as bez_kategorie %}
                {% if bez_kategorie %}
                    <tr class="red">
                        <td>-</td>
                        <td colspan="4">nezařazení do žádné z kategorií</td>
                        <td title="{{ bez_kategorie|join:'/n' }}" style="cursor: help;">
                            {{ bez_kategorie|length }}
                            <i class="ui users icon"></i>
                        </td>
                    </tr>
                {% endif %}
            {% endwith %}
        </tbody>
    </table>

    {% if kluby %}
        <h3>Kluby poháru</h3>
        <table class="ui celled table">
            <thead>
                <tr>
                    <th>název klubu</th>
                    <th>počet závodníků v poháru</th>
                </tr>
            </thead>
            <tbody>
            {% for klub, zavodniku in kluby %}
                <tr>
                    <td>{{ klub.nazev }}</td>
                    <td>{{ zavodniku }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}

{% endblock content %}

templates/pohary/pohar_list.html
{% extends 'base.html' %}
{% load l10n %}

{% block title %}
    POHÁRY | přehled
{% endblock title %}

{% block section %}section_pohary{% endblock %}

{% block header %}
    <h1 class="ui header">
        <i class="ui trophy big icon"></i>
        <div class="content">
            Poháry
            <div class="sub header">přehled pohárů</div>
        </div>
    </h1>    
{% endblock header %}

{% block staff %}
    {% if user.is_staff %}
        <div class="ui stacked secondary segment noprint">
            <a href="{% url 'pohary:pohar_create' %}" class="ui blue icon button">
                <i class="plus icon"></i>
                přidat pohár
            </a>
            <a href="{% url 'admin:pohary_pohar_changelist' %}" class="ui black icon button">
                <i class="settings icon"></i>
                admin pohárů
            </a>
        </div>
    {% endif %}
{% endblock staff %}

{% block content %}
    <table class="ui celled unstackable collapsing table">
        <thead>
            <tr>
                <th>název</th>
                <th>datum</th>
                <th>ročníky</th>
            </tr>
        </thead>
        <tbody>
            {% for pohar in object_list %}
                <tr>
                    <td>
                        <a href="{{ pohar.get_absolute_url }}">
                            {{ pohar.nazev }}
                        </a>
                    </td>
                    <td>
                        {{ pohar.datum }}
                    </td>
                    <td>
                        {% for rocnik in pohar.rocniky.all %}
                            <a href="{{ rocnik.get_absolute_url }}">
                                {{ rocnik }}
                            </a>
                            {% if not forloop.last %}
                                &nbsp;|&nbsp;
                            {% endif %}
                        {% endfor %}
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan=5>
                        žádný pohár
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}