hanes/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    path('zavody/',
        include('zavody.urls', namespace='zavody')),
    path('lide/',
        include('lide.urls', namespace='lide')),
    path('kluby/',
        include('kluby.urls', namespace='kluby')),
    path('zavodnici/',
        include('zavodnici.urls', namespace='zavodnici')),
    path('pohary/',
        include('pohary.urls', namespace='pohary')),

    path('zalohovat_databazi/',
        login_required(views.backup_database), name='backup_database'),
    path('flatpages/editace/<int:pk>/',
        login_required(views.FlatPageUpdate.as_view()), name='flatpage_editace'),
    path('',
        views.uvod, {'url': '/uvod/'}, name='uvod'),

    # django
    path('admin/', admin.site.urls),
    path('accounts/',
        include('django.contrib.auth.urls')),
]

if settings.TEMPLATE_DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

kluby/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import *

app_name = 'kluby'
urlpatterns = [
    # LISTs
    path('',
        KlubyListView.as_view(), name='kluby_list'),

    # DETAILs
    path('detail/<str:slug>/',
        KlubDetailView.as_view(), name='klub_detail'),
    path('editace/<str:slug>/',
        login_required(KlubUpdateView.as_view()), name='klub_update'),

    # AUTOCOMPLETEs
    path('klub_autocomplete/',
        klub_autocomplete, name='klub_autocomplete'),
]

lide/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import *

app_name='lide'
urlpatterns = [
    # LISTs
    path('',
        clovek_list, name='lide_list'),

    # DETAILs
    path('detail/<str:slug>/',
        ClovekDetailView.as_view(), name='clovek_detail'),
    path('editace/<str:slug>/',
        login_required(clovek_update), name='clovek_update'),

    # IMPORTs
    path('import_csv/',
        LideImportCSV.as_view(), name='import_csv'),

    # AUTOCOMPLETEs
    path('clovek_autocomplete/',
        clovek_autocomplete, name='clovek_autocomplete'),
    path('rocnik/<int:rocnik_pk>/clovek_autocomplete/',
        clovek_autocomplete, name='clovek_autocomplete'),

    # UTILITY
    path('duplicity/',
        duplicity, name='duplicity'),
]

zavody/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required

from .views import *

app_name='zavody'
urlpatterns = [
    # LISTs
    path('',
        ZavodyListView.as_view(),
        name='zavody_list'),

    # DETAILs
    path('detail/<int:pk>/',
        ZavodDetailView.as_view(),
        name='zavod_detail'),
    path('rocnik/<int:pk>/detail/',
        RocnikDetailView.as_view(),
        name='rocnik_detail'),
    path('rocnik/<int:pk>/startovne/',
        StartovneRocnikuDetailView.as_view(),
        name='startovne_rocniku_detail'),
    path('kategorie/<int:pk>/',
        KategorieDetailView.as_view(),
        name='kategorie_detail'),
    path('rocnik/<int:rocnik_pk>/vysledkova_listina/',
        vysledkova_listina,
        name='vysledkova_listina'),
    path('rocnik/<int:pk>/startovni_casy/',
        login_required(StartovniCasyView.as_view()),
        name='startovni_casy'),

    # CREATEs
    path('zavod/novy/',
        ZavodPridejView.as_view(),
        name='zavod_pridani'),
    path('<str:slug>/rocnik/novy/',
        RocnikPridejView.as_view(),
        name='rocnik_pridani'),

    # UPDATEs
    path('rozkategorizovat_zavodniky/<int:rocnik_pk>/',
        login_required(rozkategorizovat_zavodniky),
        name='rozkategorizovat_zavodniky'),
    path('formular_startera/<int:rocnik_pk>/',
        login_required(formular_startera),
        name='formular_startera'),
    path('zavod/<int:pk>/editace/',
        ZavodUpdateView.as_view(),
        name='zavod_editace'),
    path('rocnik/<int:pk>/editace/',
        RocnikUpdateView.as_view(),
        name='rocnik_editace'),
    path('kategorie/<int:pk>/editace/',
        KategorieUpdateView.as_view(),
        name='kategorie_editace'),

    # DELETE
    path('rocnik/<int:pk>/smazat/',
        RocnikDeleteView.as_view(),
        name='rocnik_smazani'),
    path('zavod/<int:pk>/smazat/',
        ZavodDeleteView.as_view(),
        name='zavod_smazani'),
    # path('kategorie/<int:pk>/smazat/',
    #     KategorieDeleteView.as_view(),
    #     name='kategorie_smazani'),

    # FORMs
    path('pridani_zavodniku/rocnik/<int:pk>/',
        login_required(pridani_zavodniku),
        name='pridani_zavodniku'),
    path('import_zavodniku/rocnik/<int:pk>/',
        login_required(ImportZavodnikuView.as_view()),
        name='import_zavodniku'),
    path('rocnik/<int:rocnik_pk>/startovni_listina/',
        startovni_listina,
        name='startovni_listina'),
    path('rocnik/<int:rocnik_pk>/startovni_listina/<str:ordering_str>/',
        startovni_listina,
        name='startovni_listina'),
    path('rocnik/<int:rocnik_pk>/cilovy_formular/',
        login_required(cilovy_formular),
        name='cilovy_formular'),
    path('rocnik/<int:rocnik_pk>/import_souboru_casu/txt/',
        login_required(ImportCasuSouborView.as_view()),
        name='import_souboru_casu_txt'),
    path('rocnik/<int:rocnik_pk>/import_textu_casu/',
        login_required(ImportCasuTextView.as_view()),
        name='import_textu_casu'),
    path('rocnik/<int:rocnik_pk>/zpracovani_importovanych_casu/txt/',
        login_required(ZpracovaniImportovanychCasuTxtView.as_view()),
        name='zpracovani_importovanych_casu_txt'),

    # AJAX
    path('kategorie/<int:pk>/startovni_casy/upravit/',
        login_required(AjaxKategorieStartovniCasyUpdateView.as_view()),
        name='ajax_kategorie_startovni_casy_update'),

    # EXPORT
    path('rocnik/<int:rocnik_pk>/startovka_export/',
        startovka_export,
        name='startovka_export'),
    path('rocnik/<int:rocnik_pk>/startovka_export/<str:ordering_str>/',
        startovka_export,
        name='startovka_export'),
    path('rocnik/<int:rocnik_pk>/vysledky_export/',
        vysledky_export,
        name='vysledky_export'),
    path('rocnik/<int:rocnik_pk>/kategorie_export/',
        kategorie_export,
        name='kategorie_export'),

    path('kategorie/<int:kategorie_pk>/pdf/vysledkova_listina/',
        vysledky_kategorie_PDF,
        name='vysledky_kategorie_PDF'),
    path('rocnik/<int:rocnik_pk>/pdf/vysledkova_listina/',
        vysledky_rocnik_PDF,
        name='vysledky_rocnik_PDF'),
    path('kategorie/<int:kategorie_pk>/pdf/startovni_listina/',
        startovka_kategorie_PDF,
        name='startovka_kategorie_PDF'),
    path('rocnik/<int:rocnik_pk>/pdf/startovni_listina/',
        startovka_rocnik_PDF,
        name='startovka_rocnik_PDF'),

    # AUTOCOMPLETEs
    path('sport_autocomplete/', sport_autocomplete, name='sport_autocomplete'),
    path('zavod_autocomplete/', zavod_autocomplete, name='zavod_autocomplete'),
]

lide/views.py
import json

from django.contrib import messages
from django.db.models import Count
from django.forms.models import inlineformset_factory
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.template import RequestContext
from django.urls import reverse, reverse_lazy
from django.utils.text import slugify
from django.views.generic import DetailView
from django.views.generic.edit import FormView

from zavody.models import Rocnik

from .forms import ClovekUpdateForm, LideImportCSVForm
from .models import Clenstvi, Clovek


def _referer_do_session(request):
    referer = request.META.get('HTTP_REFERER', '')
    if not referer.endswith(request.path):
        request.session['referer'] = referer

# DETAILs
class ClovekDetailView(DetailView):
    model = Clovek
    context_object_name = 'clovek'
    template_name = 'lide/clovek_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ClovekDetailView, self).get_context_data(**kwargs)
        context['zavodnici'] = self.object.zavodnici.filter(kategorie_temp__isnull=False).order_by('-rocnik__datum')
        context['jmenovci'] = Clovek.objects.filter(
            prijmeni__istartswith=self.object.prijmeni.rstrip('ová')).exclude(pk=self.object.pk)
        _referer_do_session(self.request)
        context['referer'] = self.request.session.get('referer', None)
        return context


class LideImportCSV(FormView):
    form_class = LideImportCSVForm
    template_name = 'lide/staff/lide_import_csv.html'
    success_url = reverse_lazy('lide:lide_list')

    def form_valid(self, form):
        lide = form.save()
        novy_lide, nove_kluby = 0, 0
        for radek in lide:
            if radek[2]:
                novy_lide += 1
            if radek[3]:
                nove_kluby += 1
        if novy_lide:
            messages.success(
                self.request,
                'Přidáno {0} lidí do seznamu.'.format(novy_lide))
        if nove_kluby:
            messages.success(
                self.request,
                'Přidáno {0} klubů do seznamu.'.format(nove_kluby))
        if not any((novy_lide, nove_kluby)):
            messages.warning(
                self.request,
                'Nebylo nic přidáno!')
        return super(LideImportCSV, self).form_valid(form)


def clovek_update(request, slug):
    'editace cloveka'
    clovek = Clovek.objects.get(slug=slug)
    zavodnici = clovek.zavodnici.filter(kategorie_temp__isnull=False).order_by('-rocnik__datum')
    jmenovci = Clovek.objects.filter(
            prijmeni__istartswith=clovek.prijmeni.rstrip('ová')).exclude(slug=clovek.slug)
    ClenstviFormSet = inlineformset_factory(
        Clovek,
        Clenstvi,
        extra=1,
        fields=('klub', 'sport', 'priorita'))
    if request.method == 'POST':
        form = ClovekUpdateForm(request.POST, instance=clovek)
        clenstvi_formset = ClenstviFormSet(request.POST, instance=clovek)
        if form.is_valid() and clenstvi_formset.is_valid():
            clovek, zpravy, smazan = form.save()  # clovek se zde muze zmenit.
            request.session['smazano'] = smazan
            for zprava in zpravy:
                messages.success(request, zprava)
            if clovek:
                clenstvi_formset.instance = clovek
                clenstvi_formset.save()
                return HttpResponseRedirect(clovek.get_absolute_url(request.user))
            else:
                # pokud byl klub smazan a nebyl urcen novy klub clenum, pak presmeruj na seznam klubu
                return HttpResponseRedirect(reverse('lide:lide_list'))
        else:
            messages.error(request, 'Chyba ve formuláři!!')
    else:
        if not request.session.get('smazano', None):
        # if 'smazano' not in request.session or not request.session['smazano']:
            _referer_do_session(request)
        else:
            request.session['smazano'] = False
            request.session['referer'] = None
        form = ClovekUpdateForm(instance=clovek)
        clenstvi_formset = ClenstviFormSet(instance=clovek)
    return render(request,
        'lide/staff/clovek_editace.html', {
            'clovek': clovek,
            'zavodnici': zavodnici,
            'jmenovci': jmenovci,
            'form': form,
            'clenstvi_formset': clenstvi_formset,
            'referer': request.session.get('referer', None)},
        )


def clovek_list(request):
    lide = Clovek.objects.all().annotate(
        pocet_zavodu=Count('zavodnici'))
    for clovek in lide:
        clovek.kluby = clovek.clenstvi.values_list('klub', flat=True).distinct()
    return render(request,
        'lide/clovek_list.html',
        {'lide': lide},
        )


def clovek_autocomplete(request, rocnik_pk=None):
    vysledek = []
    if rocnik_pk:
        rocnik = Rocnik.objects.get(pk=rocnik_pk)
    if 'query' in request.GET:
        # query rozdeli na dle mezery na prijmeni a jmeno 
        query = slugify(request.GET['query']).split('-')
        lide = Clovek.objects.filter(prijmeni_slug__startswith=query[0])
        if len(query) > 1:
            lide = lide.filter(jmeno_slug__startswith=query[1])

        for clovek in lide:
            zavodnik_oznac = ''
            if rocnik:
                serazene_clenstvi = clovek.serazene_clenstvi_pro_zavod(rocnik.zavod)
                zavodnik = rocnik.zavodnici.filter(clovek=clovek).first()
                if zavodnik:
                    zavodnik_oznac = zavodnik.cislo or '???'
            else:
                serazene_clenstvi = None
            vysledek.append({
                'value': clovek.prijmeni,
                'data': {
                    'prijmeni': clovek.prijmeni,
                    'jmeno': clovek.jmeno,
                    'pohlavi': clovek.pohlavi,
                    'narozen': clovek.narozen,
                    'klub': serazene_clenstvi[0].klub.nazev if serazene_clenstvi else '',
                    'zavodnik': zavodnik_oznac,
                    'clovek_id': clovek.id
                }
            })
        # seradit dle klubu, kvuli groupovani v napovede
        vysledek.sort(key=lambda i: (i['data']['klub'], i['value']))
    return HttpResponse(
        json.dumps({'suggestions': vysledek}),
        content_type='application/json')


# UTILITY
def duplicity(request):
    seen = set()
    duplicity = set()
    for clovek in Clovek.objects.all():
        x = clovek.prijmeni_slug + '-' + clovek.jmeno_slug
        if x not in seen:
            seen.add(x)
        else:
            duplicity.add(clovek)
    return HttpResponse('<br>'.join([str(x) for x in duplicity]))

templates/lide/staff/clovek_editace.html
{% extends 'base.html' %}
{% load l10n custom_filters %}

{% block title %}
    EDITACE | {{ clovek }}
{% endblock title %}

{% block custom_js %}
    <script type="text/javascript">
        var clovek_autocomplete_url = "{% url 'lide:clovek_autocomplete' %}";
    </script>
{% endblock custom_js %}

{% block section %}section_lide{% endblock section %}

{% block breadcrumb %}
    <div class="ui breadcrumb">
        <a href="{% url 'lide:lide_list' %}#{{ clovek.prijmeni.0 }}" class="section">lidé</a>
        <i class="right chevron icon divider"></i>
        <div class="active section">editace člověka</div>
    </div>
{% endblock breadcrumb %}

{% block header %}
    <h1 class="ui header">
        {% if referer %}
            <a href="{{ referer }}" title="zpět na předchozí stránku">
                <i class="ui reply mail link big icon"></i>
            </a>
        {% else %}
            <a href="{% url 'lide:lide_list' %}#{{ clovek.prijmeni.0 }}" title="zpět na seznam lidí">
                <i class="ui reply mail link big icon"></i>
            </a>
        {% endif %}
        <div class="content">
            <i class="ui user big icon"></i>
            {{ clovek.cele_jmeno }}
            {% if user.is_staff %}
                <a href="{% url 'admin:lide_clovek_change' clovek.id %}" title="editovat člověka" target="_blank" class="ui icon black button">
                    <i class="settings link icon"></i>
                </a>
            {% endif %}
            <div class="sub header">editace človeka</div>
        </div>
    </h1>
{% endblock header %}

{% block staff %}
    <div class="ui stacked secondary sticky segment right aligned">
        <button type="submit" class="ui primary icon button" form="clovek_form">
            <i class="save icon"></i>
            odeslat
        </button>
        {% if referer %}
            <a href="{{ referer }}" title="neuložit změny a zpět na předchozí stránku lidí" class="ui icon button">
                <i class="ui reply mail icon"></i>
                zrušit
            </a>
        {% else %}
            <a href="{% url 'lide:lide_list' %}#{{ clovek.prijmeni.0 }}" title="neuložit změny a zpět na seznam lidí" class="ui icon button">
                <i class="ui reply mail icon"></i>
                zrušit
            </a>
        {% endif %}
    </div>
{% endblock staff %}

{% block content %}
    <form action="" method="post" class="ui {% if form.errors or clenstvi_formset.errors %}error{% endif %} form" id="clovek_form">

        <div class="ui stackable grid">

            {# PRVNI SLOUPEC #}
            <div class="sixteen wide tablet six wide computer column">
                <h3 class="ui dividing header">
                    Člověk
                </h3>

                <div class="ui error message">
                    {{ form.non_field_errors.0|safe }}
                </div>

                {% csrf_token %}
                {% for field in form %}
                    {% include "elements/_form_error_field.html" with label=True help=True %}
                {% endfor %}
            </div>

            {# DRUHY SLOUPEC #}
            <div class="sixteen wide tablet six wide computer column">
                <h3 class="ui dividing header">
                    Členství v klubech
                </h3>

                <div class="ui error message">
                    {{ clenstvi_formset.non_form_errors }}
                </div>

                <div class="ui info small message">
                    <i class="info icon"></i>
                    Členství je u člověka použito pro nabízení vhodných klubů.
                    Jeho odstraněním se kluby ani jejich přiřazení k závodu nesmažou.
                </div>
                {{ clenstvi_formset.management_form }}
                {% for clenstvi_form in clenstvi_formset %}
                    <div class="ui secondary segment">
                        {% for field in clenstvi_form %}
                            {% include "elements/_form_error_field.html" with label=True help=True %}
                        {% endfor %}
                        {% include "elements/_error_pointing_ label.html" with error=clenstvi_form.non_field_errors.0 %}
                    </div>
                {% endfor %}
            </div>

            {# TRETI SLOUPEC #}
            <div class="sixteen wide tablet four wide computer column">
                    <h3 class="ui dividing header">Jmenovci</h3>
                    {% if jmenovci %}
                        <ul>
                            {% for jmenovec in jmenovci %}
                                <li>
                                    <a href="{% detail_url jmenovec %}">
                                        {{ jmenovec }}
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    {% endif %}
            </div>
        </div>
    </form>

    <table class="ui unstackable celled structured table">
        <thead>
            <tr>
                <th colspan="6">zúčastněné závody</th>
                <th colspan="4" class="center aligned">umístění v závodu</th>
            </tr>
            <tr>
                <th rowspan="2" class="center aligned">ročník</th>
                <th rowspan="2" class="center aligned">závod</th>
                <th rowspan="2" class="center aligned">za klub</th>
                <th rowspan="2" class="center aligned">kategorie</th>
                <th rowspan="2" class="center aligned">trať</th>
                <th rowspan="2" class="center aligned">výsledný čas</th>
                <th colspan="2" class="center aligned">v kategorii</th>
                <th colspan="2" class="center aligned">na trati</th>
            </tr>
            <tr>
                <th class="right aligned">umístění</th>
                <th class="right aligned" title="celkem závodníků v kategorii">Σ</th>
                <th class="right aligned">umístění</th>
                <th class="right aligned" title="celkem závodníků na trati">Σ</th>
            </tr>
        </thead>
        <tbody>
            {% regroup zavodnici|dictsortreversed:'rocnik.datum' by rocnik.datum|date:'Y' as roky_list %}
            {% for rok in roky_list %}
                {% for zavodnik in rok.list %}
                    <tr>
                        {% if forloop.first %}
                            <td rowspan="{{ rok.list|length }}" class="center aligned">
                                {{ rok.grouper }}
                            </td>
                        {% endif %}
                        <td>
                            <a href="{% url 'zavody:vysledkova_listina' zavodnik.rocnik.id %}#zavodnik_{{ zavodnik.id|safe }}" title="{{ zavodnik.rocnik.datum }} - na výsledkovou listinu závodu">
                                {{ zavodnik.rocnik.zavod.nazev }}
                            </a>
                        </td>
                        <td>
                            <a href="{% detail_url zavodnik.klub %}">
                                {{ zavodnik.klub }}
                            </a>
                        </td>
                        <td>
                            {{ zavodnik.kategorie_temp.nazev }}
                        </td>
                        <td>
                            {{ zavodnik.kategorie_temp.delka_trate }}
                        </td>
                        <td>
                            {{ zavodnik.vysledny_cas|desetiny_sekundy|default:'' }}
                        </td>
                        <td class="right aligned">
                            {{ zavodnik.poradi_v_kategorii|default:'' }}
                        </td>
                        <td class="right aligned">
                            {{ zavodnik.kategorie_temp.zavodnici_temp.count }}
                        </td>
                        <td class="right aligned">
                            {{ zavodnik.poradi_na_trati|default:'' }}
                        </td>
                        <td class="right aligned">
                            {% if zavodnik.zavodniku_na_trati %}
                                {{ zavodnik.zavodniku_na_trati|default:'' }}
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}

            {% empty %}
                <tr>
                    <td colspan="9" class="center aligned">
                        žádný závod
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

templates/lide/staff/klub_editace.html
{% extends 'base.html' %}
{% load l10n custom_filters %}

{% block custom_js %}
    <script type="text/javascript">
        var klub_autocomplete_url = "{% url 'kluby:klub_autocomplete' %}";
    </script>
{% endblock custom_js %}

{% block title %}
    EDITACE | {{ klub.nazev }}
{% endblock title %}

{% block section %}section_kluby{% endblock section %}

{% block breadcrumb %}
    <div class="ui breadcrumb">
        <a href="{% url 'kluby:kluby_list' %}" class="section">kluby</a>
        <i class="right chevron icon divider"></i>
        <div class="active section">editace klubu</div>
    </div>
{% endblock breadcrumb %}

{% block header %}
    <h1 class="ui header">
        {% if referer %}
            <a href="{{ referer }}" title="zpět na předchozí stránku">
                <i class="ui reply mail link big icon"></i>
            </a>
        {% else %}
            <a href="{% url 'kluby:kluby_list' %}#{{ klub.nazev.0 }}" title="zpět na seznam klubů">
                <i class="ui reply mail link big icon"></i>
            </a>
        {% endif %}
        <div class="content">
            <i class="ui users big icon"></i>
            {{ klub.nazev }}
            {% if user.is_staff %}
                <a href="{% url 'admin:kluby_klub_change' klub.id %}" title="editovat klub v administraci" target="_blank" class="ui icon black button">
                    <i class="settings link icon"></i>
                </a>
            {% endif %}
            <div class="sub header">editace klubu</div>
        </div>
    </h1>
{% endblock header %}

{% block content %}
    <div class="ui stackable grid">
        <div class="sixteen wide tablet ten wide computer column">

            <form action="" method="post" class="ui form" id="klub_form">
                {% csrf_token %}
                {% for field in form %}
                    {% include "elements/_form_error_field.html" with label=True %}
                {% endfor %}
                {{ form.non_field_errors }}

                <button type="submit" class="ui primary icon button">
                    <i class="save icon"></i>
                    odeslat
                </button>
                {% if referer %}
                    <a href="{{ referer }}" title="neuložit změny a zpět na předchozí stránku" class="ui icon button">
                        <i class="ui reply mail icon"></i>
                        zrušit
                    </a>
                {% else %}
                    <a href="{% url 'kluby:kluby_list' %}#{{ klub.nazev.0 }}" title="neuložit změny a zpět na seznam klubů" class="ui icon button">
                        <i class="ui reply mail icon"></i>
                        zrušit
                    </a>
                {% endif %}
            </form>
        </div>

        <div class="sixteen wide tablet six wide computer column">
                <table class="ui unstackable celled compact small table">
                    <thead>
                        <tr>
                            <th colspan="3">
                                celkem {{ clenove|length }}  závodníků
                            </th>
                        </tr>
                        <tr>
                            <th>příjmení</th>
                            <th>jméno</th>
                            <th>narozen(a)</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for clovek in clenove %}
                            <tr>
                                <td>
                                    <a href="{% detail_url clovek %}" title="na detail člověka">
                                        {{ clovek.prijmeni }}
                                    </a>
                                </td>
                                <td>
                                    {{ clovek.jmeno }}
                                </td>
                                <td>
                                    {{ clovek.narozen|unlocalize }}
                                </td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan=3>
                                    žádný závodník
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
        </div>
    </div>
{% endblock content %}

templates/lide/staff/lide_import_csv.html
{% extends 'base.html' %}
{% load l10n %}

{% block title %}
    IMPORT | lidé CSV
{% endblock title %}

{% block custom_js %}{% endblock %}

{% block section %}section_lide{% endblock %}

{% block header %}
    <h1 class="ui header">
        <i class="ui user big icon"></i>
        <div class="content">
            Import lidí ze souboru CSV
        </div>
    </h1>    
{% endblock header %}

{% block staff %}
{% endblock staff %}

{% block content %}
    <form method="POST" action="." enctype="multipart/form-data" class="ui form">
        {% csrf_token %}
        
            <div class="field {% if form.soubor.errors %}error{% endif %}">
                <label class="underlined">
                    {{ form.soubor.label }}
                    <i class="circle help icon" title="{{ form.soubor.help_text }}"></i>
                </label>

                {{ form.soubor }}

                {% if form.soubor.errors %}
                    <div class="ui red inverted segment">
                        {{ form.soubor.errors }}
                    </div>                    
                {% endif %}

            </div>

        <button type="submit" class="ui primary icon button">
            <i class="save icon"></i>
            odeslat
        </button>
        <a href="{% url 'lide:lide_list' %}" title="neuložit a zpět" class="ui icon button">
            <i class="ui reply mail icon"></i>
            zrušit
        </a>           
    </form>           
{% endblock content %}