hanes/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    path('zavody/',
        include('zavody.urls', namespace='zavody')),
    path('lide/',
        include('lide.urls', namespace='lide')),
    path('kluby/',
        include('kluby.urls', namespace='kluby')),
    path('zavodnici/',
        include('zavodnici.urls', namespace='zavodnici')),
    path('pohary/',
        include('pohary.urls', namespace='pohary')),

    path('zalohovat_databazi/',
        login_required(views.backup_database), name='backup_database'),
    path('flatpages/editace/<int:pk>/',
        login_required(views.FlatPageUpdate.as_view()), name='flatpage_editace'),
    path('',
        views.uvod, {'url': '/uvod/'}, name='uvod'),

    # django
    path('admin/', admin.site.urls),
    path('accounts/',
        include('django.contrib.auth.urls')),
]

if settings.TEMPLATE_DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

kluby/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import *

app_name = 'kluby'
urlpatterns = [
    # LISTs
    path('',
        KlubyListView.as_view(), name='kluby_list'),

    # DETAILs
    path('detail/<str:slug>/',
        KlubDetailView.as_view(), name='klub_detail'),
    path('editace/<str:slug>/',
        login_required(KlubUpdateView.as_view()), name='klub_update'),

    # AUTOCOMPLETEs
    path('klub_autocomplete/',
        klub_autocomplete, name='klub_autocomplete'),
]

lide/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import *

app_name='lide'
urlpatterns = [
    # LISTs
    path('',
        clovek_list, name='lide_list'),

    # DETAILs
    path('detail/<str:slug>/',
        ClovekDetailView.as_view(), name='clovek_detail'),
    path('editace/<str:slug>/',
        login_required(clovek_update), name='clovek_update'),

    # IMPORTs
    path('import_csv/',
        LideImportCSV.as_view(), name='import_csv'),

    # AUTOCOMPLETEs
    path('clovek_autocomplete/',
        clovek_autocomplete, name='clovek_autocomplete'),
    path('rocnik/<int:rocnik_pk>/clovek_autocomplete/',
        clovek_autocomplete, name='clovek_autocomplete'),

    # UTILITY
    path('duplicity/',
        duplicity, name='duplicity'),
]

pohary/urls.py
from django.urls import path
from . import views


app_name = 'pohary'
urlpatterns = [
    # LISTs
    path('',
        views.PoharyListView.as_view(),
        name='pohary_list'),

    # DETAILs
    path('detail/<str:slug>/',
        views.PoharDetailView.as_view(),
        name='pohar_detail'),
    path('kategorie/<int:pk>/',
        views.KategoriePoharuDetailView.as_view(),
        name='kategorie-poharu_detail'),
    path('pridat/',
        views.PoharCreateView.as_view(),
        name='pohar_create'),
]

zavody/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required

from .views import *

app_name='zavody'
urlpatterns = [
    # LISTs
    path('',
        ZavodyListView.as_view(),
        name='zavody_list'),

    # DETAILs
    path('detail/<int:pk>/',
        ZavodDetailView.as_view(),
        name='zavod_detail'),
    path('rocnik/<int:pk>/detail/',
        RocnikDetailView.as_view(),
        name='rocnik_detail'),
    path('rocnik/<int:pk>/startovne/',
        StartovneRocnikuDetailView.as_view(),
        name='startovne_rocniku_detail'),
    path('kategorie/<int:pk>/',
        KategorieDetailView.as_view(),
        name='kategorie_detail'),
    path('rocnik/<int:rocnik_pk>/vysledkova_listina/',
        vysledkova_listina,
        name='vysledkova_listina'),
    path('rocnik/<int:pk>/startovni_casy/',
        login_required(StartovniCasyView.as_view()),
        name='startovni_casy'),

    # CREATEs
    path('zavod/novy/',
        ZavodPridejView.as_view(),
        name='zavod_pridani'),
    path('<str:slug>/rocnik/novy/',
        RocnikPridejView.as_view(),
        name='rocnik_pridani'),

    # UPDATEs
    path('rozkategorizovat_zavodniky/<int:rocnik_pk>/',
        login_required(rozkategorizovat_zavodniky),
        name='rozkategorizovat_zavodniky'),
    path('formular_startera/<int:rocnik_pk>/',
        login_required(formular_startera),
        name='formular_startera'),
    path('zavod/<int:pk>/editace/',
        ZavodUpdateView.as_view(),
        name='zavod_editace'),
    path('rocnik/<int:pk>/editace/',
        RocnikUpdateView.as_view(),
        name='rocnik_editace'),
    path('kategorie/<int:pk>/editace/',
        KategorieUpdateView.as_view(),
        name='kategorie_editace'),

    # DELETE
    path('rocnik/<int:pk>/smazat/',
        RocnikDeleteView.as_view(),
        name='rocnik_smazani'),
    path('zavod/<int:pk>/smazat/',
        ZavodDeleteView.as_view(),
        name='zavod_smazani'),
    # path('kategorie/<int:pk>/smazat/',
    #     KategorieDeleteView.as_view(),
    #     name='kategorie_smazani'),

    # FORMs
    path('pridani_zavodniku/rocnik/<int:pk>/',
        login_required(pridani_zavodniku),
        name='pridani_zavodniku'),
    path('import_zavodniku/rocnik/<int:pk>/',
        login_required(ImportZavodnikuView.as_view()),
        name='import_zavodniku'),
    path('rocnik/<int:rocnik_pk>/startovni_listina/',
        startovni_listina,
        name='startovni_listina'),
    path('rocnik/<int:rocnik_pk>/startovni_listina/<str:ordering_str>/',
        startovni_listina,
        name='startovni_listina'),
    path('rocnik/<int:rocnik_pk>/cilovy_formular/',
        login_required(cilovy_formular),
        name='cilovy_formular'),
    path('rocnik/<int:rocnik_pk>/import_souboru_casu/txt/',
        login_required(ImportCasuSouborView.as_view()),
        name='import_souboru_casu_txt'),
    path('rocnik/<int:rocnik_pk>/import_textu_casu/',
        login_required(ImportCasuTextView.as_view()),
        name='import_textu_casu'),
    path('rocnik/<int:rocnik_pk>/zpracovani_importovanych_casu/txt/',
        login_required(ZpracovaniImportovanychCasuTxtView.as_view()),
        name='zpracovani_importovanych_casu_txt'),

    # AJAX
    path('kategorie/<int:pk>/startovni_casy/upravit/',
        login_required(AjaxKategorieStartovniCasyUpdateView.as_view()),
        name='ajax_kategorie_startovni_casy_update'),

    # EXPORT
    path('rocnik/<int:rocnik_pk>/startovka_export/',
        startovka_export,
        name='startovka_export'),
    path('rocnik/<int:rocnik_pk>/startovka_export/<str:ordering_str>/',
        startovka_export,
        name='startovka_export'),
    path('rocnik/<int:rocnik_pk>/vysledky_export/',
        vysledky_export,
        name='vysledky_export'),
    path('rocnik/<int:rocnik_pk>/kategorie_export/',
        kategorie_export,
        name='kategorie_export'),

    path('kategorie/<int:kategorie_pk>/pdf/vysledkova_listina/',
        vysledky_kategorie_PDF,
        name='vysledky_kategorie_PDF'),
    path('rocnik/<int:rocnik_pk>/pdf/vysledkova_listina/',
        vysledky_rocnik_PDF,
        name='vysledky_rocnik_PDF'),
    path('kategorie/<int:kategorie_pk>/pdf/startovni_listina/',
        startovka_kategorie_PDF,
        name='startovka_kategorie_PDF'),
    path('rocnik/<int:rocnik_pk>/pdf/startovni_listina/',
        startovka_rocnik_PDF,
        name='startovka_rocnik_PDF'),

    # AUTOCOMPLETEs
    path('sport_autocomplete/', sport_autocomplete, name='sport_autocomplete'),
    path('zavod_autocomplete/', zavod_autocomplete, name='zavod_autocomplete'),
]

templates/__404.html
<!DOCTYPE html>
<html>
<head>
    <title>Stránka nenalezena</title>
</head>
<body>
    <h1>Stránka nenalezena</h1>
</body>
</html>

templates/base.html
{% load i18n static custom_filters %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>


<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

    <title>
        {% block title %}HANES{% endblock title %}
    </title>

    <link href="{% static 'semantic-ui/dist/semantic.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link href="{% static 'css/print.css' %}" rel="stylesheet" media="print">
    {% block custom_css %}{% endblock custom_css %}

    <script src="{% static 'js/jquery.js' %}" type="text/javascript"></script>
    {#<script src="{% static 'js/jquery-ui.min.js' %}" type="text/javascript"></script>#}
    <script src="{% static 'semantic-ui/dist/semantic.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery.autocomplete.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/base.js' %}" type="text/javascript"></script>
    {% block custom_js %}{% endblock custom_js %}
</head>


<body id="{% block section %}section_uvod{% endblock %}" class="{% block body_class %}{% endblock %}">

    <div class="ui blue inverted stackable menu" id="main_menu">
        <div class="header item" id="menu_uvod"
            title="{{ 'git_sha.txt'|include_if_exists }} - {{ 'git_msg.txt'|include_if_exists }}"
        >
            <a href="{% url 'uvod' %}">
                <i class="icon sun"></i>HANES 1.0
            </a>
        </div>
        <div class="item" id="menu_zavody">
            <a href="{% url 'zavody:zavody_list' %}">
                <i class="checkered flag icon"></i>
                závody
            </a>
        </div>
        <div class="item" id="menu_lide">
            <a href="{% url 'lide:lide_list' %}">
                <i class="ui user icon"></i>
                lidé
            </a>
        </div>
        <div class="item" id="menu_kluby">
            <a href="{% url 'kluby:kluby_list' %}">
                <i class="ui users icon"></i>
                kluby
            </a>
        </div>
        <div class="item" id="menu_pohary">
            <a href="{% url 'pohary:pohary_list' %}">
                <i class="ui trophy icon"></i>
                poháry
            </a>
        </div>

        <div class="right menu">
            {% if user.is_staff %}
                <div class="item">
                    <a href="{% url 'backup_database' %}" id="backup_database" title="zálohovat soubor databáze do adresáře '_BACKUP_'">
                        <i class="cloud upload link icon"></i>
                    </a>
                </div>
                <div class="item" id="menu_admin">
                    <a href="{% url 'admin:index' %}" title="do administrace databáze" target="_blank">
                        <i class="settings link icon"></i> admin
                    </a>
                </div>
            {% endif %}
            {% if user.is_authenticated %}
                <div class="item" title="přihlášený uživatel">
                    <i class="user icon"></i>
                    {{ user.get_full_name|default:user }}
                </div>
                <div class="item" id="menu_login">
                    <a href="{% url 'logout' %}?next={{request.path}}" title="odhlásit se">
                        <i class="sign out link  icon"></i>
                    </a>
                </div>
            {% else %}
                <div class="item" id="menu_login">
                    <a href="{% url 'login' %}?next={{request.path}}" title="přihlásit registrovaného uživatele">
                        <i class="user link icon"></i> login
                    </a>
                </div>
            {% endif %}
        </div>
    </div>


    {% block breadcrumb %}{% endblock %}

    {% block header %}{% endblock %}

    {% block staff %}{% endblock %}

    {% if messages %}
        {% regroup messages by level_tag as messages %}
        <div id="messages">
        {% for level in messages %}
            <div class="ui {{level.grouper}} icon message">
                <i class="close icon"></i>
                {% if level.grouper == 'success' %}
                    <i class="thumbs outline up icon"></i>
                {% else %}
                    <i class="thumbs outline down icon"></i>
                {% endif %}
                <div class="content">
                    <ul class="list">
                        {% for message in level.list %}
                            <li>{{ message|safe }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% endfor %}
        </div>
    {% endif %}

    <div id="content">
        {% block content %}{% endblock %}
    </div>

    <div id="ajax_messages" class="ui compact floating message" style="display:none;"></div>

    <div id="printerDiv" style="display:none"></div>

</body>
</html>

templates/objekt_editace.html
{% extends 'base.html' %}
{% load wysiwyg %}

{% block title %}
    EDITACE | {{ object }}
{% endblock title %}

{% block header %}
    <h1 class="ui header">
        <i class="ui edit big icon"></i>
        <div class="content">
            {{ object }}
            <div class="sub header">
                editace objektu
            </div>
        </div>
    </h1>    
{% endblock header %}

{% block custom_js %}
    {% wysiwyg_setup %}    
{% endblock custom_js %}

{% block content %}
    <div class="ui container">
        <form action="" method="POST" class="ui form" {% if form.is_multipart %}enctype="multipart/form-data"{% endif %}>
            {% csrf_token %}
            {% for field in form %}
                {% include "elements/_form_error_field.html" with label=True %}
            {% endfor %}

            <button type="submit" class="ui primary icon button">
                <i class="save icon"></i>
                odeslat
            </button>
            <a href="{{ object.get_absolute_url }}" title="neuložit změny a zpět na detail objektu" class="ui icon button">
                <i class="cancel icon"></i>
                zrušit
            </a>
            {% if object.get_delete_url %}
                <a href="{{ object.get_delete_url }}" title="smazat objekt" class="ui icon red button">
                    <i class="trash icon"></i>
                    smazat
                </a>            
            {% endif %}
        </form>
        {% wysiwyg_editor "id_content" %}        
    </div>
{% endblock content %}

templates/objekt_smazani.html
{% extends 'base.html' %}

{% block title %}
    SMAZAT? | {{ object }}
{% endblock title %}

{% block header %}
    <h1 class="ui header">
        <i class="ui trash red big icon"></i>
        <div class="content">
            {{ object }}
            <div class="sub header">
                smazání objektu
            </div>            
        </div>
    </h1>    
{% endblock header %}

{% block content %}
    <div class="ui container">
        <form action="" method="POST" class="ui form">
            {% csrf_token %}
            <button type="submit" class="ui red icon button">
                <i class="trash icon"></i>
                smazat
            </button>
            <a href="{{ object.get_absolute_url }}" title="nemazat a zpět na detail objektu" class="ui icon button">
                <i class="cancel icon"></i>
                zrušit
            </a>
        </form>        
    </div>
{% endblock content %}

templates/pdf.html
<!DOCTYPE html>
<html>


<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

    <title>
    HANES 
     | úvod

    </title>

    <link href="/static/semantic-ui/dist/semantic.min.css" rel="stylesheet">
    <link href="/static/css/base.css" rel="stylesheet">
    <link href="/static/css/print.css" rel="stylesheet" media="print">
    

    <script src="/static/js/jquery.js" type="text/javascript"></script>
    <script src="/static/semantic-ui/dist/semantic.min.js" type="text/javascript"></script>
    <script src="/static/js/jquery.autocomplete.min.js" type="text/javascript"></script>
    <script src="/static/js/base.js" type="text/javascript"></script>
    
</head>


<body id="section_uvod">

    <div class="ui small blue inverted menu" id="main_menu">
        <div class="header item" id="menu_uvod">
            <a href="/">
                <i class="icon sun"></i>HANES 1.0
            </a>
        </div>
        <div class="item" id="menu_zavody">
            <a href="/zavody/">
                závody
            </a>
        </div>
        <div class="item" id="menu_lide">
            <a href="/lide/">
                lidé
            </a>
        </div>
        <div class="item" id="menu_kluby">
            <a href="/lide/kluby/">
                kluby
            </a>
        </div>

        <div class="right menu">
            
                <div class="item" id="menu_admin">
                    <a href="/admin/" title="do administrace databáze" target="_blank">
                        <i class="settings link icon"></i> admin
                    </a>
                </div>
            
            
                <div class="item" title="přihlášený uživatel">
                    <i class="user icon"></i>
                    Martin Hruška
                </div>
                <div class="item" id="menu_login">
                    <a href="/accounts/logout/?next=/" title="odhlásit se">
                        <i class="sign out link  icon"></i>
                    </a>
                </div>
            
        </div>
    </div>


    

    
    <h1 class="ui header">
        Julinka = zločinecká organizace
    </h1>    


    

    

    <div id="content">
        
    <p>
        nějaký úvdoní pokec, nebo cokoliv!
    </p>

    </div>

</body>


</html>

templates/uvod.html
{% extends 'base.html' %}

{% block title %}
    {{ flatpage.title|upper }}
{% endblock title %}

{% block section %}section_uvod{% endblock section %}

{% block header %}
    <h1 class="ui header">
        {{ flatpage.title }}
        {% if user.is_active %}
            <a href="{% url 'flatpage_editace' flatpage.pk %}" title="upravit obsah stránky">
                <i class="edit link icon"></i>
            </a>
        {% endif %}
        <div class="sub header">vítejte v databázi výsledků</div>
    </h1>
{% endblock header %}

{% block content %}
    {{ flatpage.content|safe|urlize|linebreaks }}

    <div class="ui four column stackable grid" id="seznam_zavodu">
        {% for zavody in zavody_seznam %}
            <div class="column">
                <table class="ui {% cycle 'green' 'yellow' 'red' 'brown' %} large padded table">
                    <thead>
                        <tr>
                            <th colspan="3">
                                {% cycle 'budoucí závody' 'závody tento týden' 'dnešní závody!' 'předcházející závody' %}
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for rocnik in zavody %}
                            <tr>
                                <td>
                                    <a href="{{ rocnik.get_absolute_url }}">
                                        {{ rocnik }}
                                    </a>
                                </td>
                                <td>
                                    {{ rocnik.datum|date:'SHORT_DATE_FORMAT' }}
                                </td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td class="disabled">
                                    žádný závod není registrován
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        {% endfor %}
    </div>
{% endblock content %}